### ISSUE TITLE
Foreign import with type signature ending with a higher kinded type broken

### ISSUE THREAD

**Issue by Maskhjarna** [Maskhjarna/tree-sitter-purescript#2]
![Screenshot from 2023-08-24 09-26-59](https://github.com/Maskhjarna/tree-sitter-purescript/assets/80115848/4d360abf-0fa3-4b6a-b1f1-c245a8773f0f)
```purescript
module Test where

foreign import f :: String -> Maybe Int
foreign import f2 :: String -> String
```

**Comment by NomisIV** [comment]
This is fixed now :)
![image](https://github.com/Maskhjarna/tree-sitter-purescript/assets/47303199/efc1b356-697a-4fa7-a6d0-9f59dbc06477)
