### ISSUE TITLE
Type functions broken

### ISSUE THREAD

**Issue by Maskhjarna** [Maskhjarna/tree-sitter-purescript#3]
![Screenshot from 2023-08-24 09-59-55](https://github.com/Maskhjarna/tree-sitter-purescript/assets/80115848/69ffcbd7-e4f1-4bd5-b4b9-3f9ae483ba4d)

```purescript
module Test where

type A :: forall k. k -> k
type A x = x
```

**Comment by postsolar** [comment]
Why was this issue closed? It's still broken
