### ISSUE TITLE
Doc-comments are not recognized as comments

### ISSUE THREAD

**Issue by NomisIV** [Maskhjarna/tree-sitter-purescript#7]
What the title says

![image](https://github.com/Maskhjarna/tree-sitter-purescript/assets/47303199/21123840-ba67-43c9-8fde-d0ff8f1c1e9a)

**Comment by postsolar** [comment]
`-- |` (note the whitespace) works though, so I'd rather title this as _**Some** doc-comments are not recognized as comments_.
